title: MREXOJO - Cloud & DevOps Infrastructure Services
baseURL: /
params:
  base_font: system-sans
  palette: purple
  header:
    logo_img: images/mrexojo-purple.png
    logo_img_alt: mrexojo cloud
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
        has_icon: false
      - label: Services
        url: /features
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: Contact
        url: /contact
        style: primary
  footer:
    sections:
      - type: footer_text
        image: images/mrexojo-white.png
        image_url: /
        image_alt: Cloud_DevOps
        content: |
          Cloud & DevOps Infrastructure Services
      - type: footer_nav
        title: MREXOJO
        nav_links:
          - label: About
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Iaac Templates
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: Add me
        nav_links:
          - label: LinkedIn
            url: 'https://www.linkedin.com/in/mrexojo'
            style: link
            has_icon: true
            icon: linkedin
            icon_position: left
          - label: GitHub
            url: 'https://github.com/mrexojo'
            style: link
            has_icon: true
            icon: github
            icon_position: left
          - label: Twitter
            url: 'https://twitter.com/mrexojo'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
      - type: footer_form
        title: Be ready!
        content: |
          Monthly Cloud Services news and training to be ready to grow
        form_id: contactForm
        hide_labels: true
        form_fields:
          - input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>.
  domain: 'https://mrexojo.com'
  favicon: images/mrexojo-purple-ed16ee72.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
